version: "3.9"

services:
    mysql:
        container_name: mysql
        image: mysql
        restart: always
        build:
            args:
                DATABASE_USERNAME: ${DATABASE_USERNAME}
                DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - D:/MySqlImage/data:/var/lib/mysql
            - D:/MySqlImage/logs:/var/log/mysql
        ports:
            - ${PORT}:${PORT}
        expose:
            - "${PORT}"